In [28]:
import pandas as pd
import numpy as np

In [29]:
country_list = ['sg', 'my', 'tw', 'id', 'th']

In [30]:
for index, country in enumerate(country_list):
    print(str(index) + ' ' + country)
    # country_list = country_list.remove(country)

0 sg
1 my
2 tw
3 id
4 th

In [31]:
country_list.remove('sg')
country_list

['my', 'tw', 'id', 'th']

In [32]:
for index, country in enumerate(country_list):
    print(str(index) + ' ' + country)

0 my
1 tw
2 id
3 th

In [33]:
country_list.remove('id')
country_list

['my', 'tw', 'th']

In [34]:
for index, country in enumerate(country_list):
    print(str(index) + ' ' + country)

0 my
1 tw
2 th

In [35]:
df = pd.DataFrame(np.random.randint(0,100,size=(100, 4)), columns=list('ABCD'))
df

     A   B   C   D
0   68  91  36   5
1   87  56  48  46
2   94  32   4  75
3   44  30  35  75
4   98  48  85  52
5   72  89  26   8
6   27  45  15  49
7   33  80   6  19
8   68  53  95  87
9   95  69   6  92
10  79  53  68  25
11  29  50  98  67
12  92  52  18  95
13  79   6   1  69
14  88  87  37  23
15  98  56  94  63
16  60  76  60  64
17   2  91  54  67
18  38  77  77  75
19  95  51  57   9
20   7  22  30  15
21  44  39  24  10
22  38  70  43  21
23  73  98   6  67
24  72  97  29  24
25  76  77   1  47
26  70  25  68  41
27  95  85  38  58
28  87  14  97  90
29  94  69  89  36
..  ..  ..  ..  ..
70  10  58  18  59
71  45  56   5  57
72  38  95  13  81
73  84   4  52   0
74  30  46  44  71
75  81   3  20  65
76  87  14  88  46
77  11   8   2  89
78  59  15   4  68
79  91  79  57   1
80  33  30  15  90
81   9  21   2  34
82   4   6  61  42
83  22  99  52   3
84  74  52  99  34
85   1  11  45   1
86  72  70  86   3
87  95  32  66  35
88  17  15  63  35
89  37  73  51  37
90   2  87  67  86
91  72  20  48  75
92  64  82  17   4
93   1  70  60  11
94  40  35  16  74
95  22  90  90  97
96  58   5  82  19
97  86  79  99  36
98  96  45  95  49
99  26  13  63  80

[100 rows x 4 columns]

In [48]:
af = df.groupby(by=['A', 'B', 'C']).sum().groupby(level=[2]).cumsum()
af

            D
A  B  C
1  11 45    1
   70 60   11
2  29 73   35
   87 67   86
   91 54   67
4  6  61   42
5  29 2    84
   77 7    64
   89 83   88
7  22 30   15
9  21 2   118
   93 50   64
10 58 18   59
11 8  2   207
13 97 48   38
14 40 75   56
17 15 63   35
19 75 59   81
22 43 31    7
   82 90   81
   90 90  178
   99 52    3
23 55 33   87
25 21 69   15
   44 38   51
26 13 63  115
27 45 15   49
29 50 98   67
30 46 44   71
31 26 3    79
...       ...
75 98 84   22
76 69 16  176
   77 1    47
77 24 27   76
78 67 2   216
79 6  1   116
   53 68   66
81 3  20   65
84 4  52    3
86 79 99   70
87 14 88   46
      97   90
   36 72   30
   56 48  159
88 87 37   23
91 79 57    8
92 39 72   71
   52 18  154
94 32 4   143
   69 89   36
95 32 66   35
   51 57   17
   64 77   81
   69 6   178
   85 38  109
96 45 95  136
   63 75   98
98 48 85  187
   56 94   63
99 98 21   83

[100 rows x 1 columns]